### PR TITLE
Merge all forks upstream + latest spago and fix tests

### PR DESCRIPTION
**Pull request by fetsorn**
There are three forks, but the tooling has changed since they were made, so I migrate upstream to the latest spago myself, and then merge features from the forks.

 - merge [kamoii/master](https://github.com/kamoii/purescript-playwright)
   - download test fix
   - connectOverCDP binding
 - merge [i-am-the-slime/es-modules](https://github.com/i-am-the-slime/purescript-playwright/tree/es-modules)
   - replace `exports.` with `export const` 
 - merge fetsorn
   - [spago@next](https://github.com/purescript/spago)
   - purescript 0.15.15
   - replace broken `Undefined.undefined` with `Data.Unit.unit`
   - fix reference leak in `effectfulGetter`, see [notes](https://chat.norcivilianlabs.org/#narrow/stream/2-team/topic/purescript.20migration/near/24459)
   - update `Stream.onDataString` to `Node.EventEmitter.on_ Stream.dataHStr` as per node-streams [changelog](https://github.com/purescript-node/purescript-node-streams/releases/tag/v8.0.0)
 - merge [i-am-the-slime/master](https://github.com/i-am-the-slime/purescript-playwright/tree/master), 
   - use `Data.Time.Duration.Milliseconds` for timeouts
 - merge photz
   - use `WebSocketEndpoint` in `connect`
 - format source code, explicit imports, fix shadowed types

### CODE REVIEW

**Comment by f-f** [comment]
@fetsorn thanks for the PR!

A few things:
- we'll need to add the new spago to CI for tests to run, currently it's running with the legacy spago
- the patch seems to have a lot of formatting changes - we can reformat files, but then we should also have a CI job that ensures that things are consistently formatted. All of this should be in a separate PR

**Comment by fetsorn** [comment]
>     * the patch seems to have a lot of formatting changes - we can reformat files, but then we should also have a CI job that ensures that things are consistently formatted. All of this should be in a separate PR

i ran prettier on all `.js` files and purs-tidy on all `.purs`. Would you like me to revert this formatting here? Or just open another PR with a format workflow after this is merged?

**Comment by f-f** [comment]
> i ran prettier on all .js files and purs-tidy on all .purs. Would you like me to revert this formatting here? Or just open another PR with a format workflow after this is merged?

All the formatting changes make it hard to review the actual code changes, so I'd prefer if we could revert them here, and open a PR with the format workflow + the formatting changes after this is merged.

We could also have a formatting PR before this one, but that might be more complicated.

**Comment by f-f** [comment]
Btw tests fail with
```
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
```

**Review by f-f — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
